name: Task
description: Define an implementation or maintenance task
title: "chore: "
labels:
  - "type: task"
  - "status: triage"
  - "priority: medium"
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What task should be done?
    validations:
      required: true
  - type: textarea
    id: purpose
    attributes:
      label: Purpose
      description: Why is this task needed?
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      placeholder: |
        - [ ] ...
    validations:
      required: true
  - type: textarea
    id: out-of-scope
    attributes:
      label: Out of Scope
      description: Optional. What should not be handled in this issue?
    validations:
      required: false
  - type: textarea
    id: notes
    attributes:
      label: Additional Context
    validations:
      required: false
